ALTER TABLE CALENDAR_BOOK ADD COLUMN CHECK_SUM VARCHAR(255);

UPDATE CALENDAR_BOOK SET CHECK_SUM = '00ZZZ';

ALTER TABLE CALENDAR_BOOK MODIFY CHECK_SUM VARCHAR(255) NOT NULL;

ALTER TABLE USER DROP COLUMN CHECK_SUM;